//
//  Trip.swift
//  Desert
//

import Foundation
import SwiftData

/// A single desert trip — stored locally in SwiftData and synced to Firebase.
@Model
class Trip {

    // MARK: - Stored — Identity

    /// Unique trip identifier — generated by Firebase, format: `trip_001_8f3k9mp2`.
    var tripId: String

    /// Display name — defaults to the start date if not provided by the user.
    var tripName: String

    /// Trip lifecycle status.
    /// - `"active"`: trip is in progress.
    /// - `"overdue"`: user has not returned by the expected return time.
    /// - `"completed"`: trip has ended safely.
    var status: String

    // MARK: - Stored — User Info

    var userName: String
    var phoneNumber: String

    // MARK: - Stored — Trip Details

    var destination: String
    var destinationLat: Double
    var destinationLng: Double
    var startTime: Date

    /// Expected return time — used to trigger overdue logic and local notifications.
    var returnTime: Date
    var endedAt: Date?
    var hasGroup: Bool
    var groupSize: Int

    // MARK: - Stored — Vehicle Info

    var carName: String
    var carColor: String
    var is4WD: Bool
    var plateLetters: String
    var plateNumbers: String

    // MARK: - Stored — Contacts

    /// Family members notified if the trip is overdue.
    var emergencyContacts: [Contact]

    /// People travelling with the user.
    var groupContacts: [Contact]

    // MARK: - Stored — Location Tracking

    /// Latitude of the last location uploaded to Firebase. `0` if not yet uploaded.
    var lastKnownLat: Double

    /// Longitude of the last location uploaded to Firebase. `0` if not yet uploaded.
    var lastKnownLng: Double

    /// Heading in degrees at the time of last upload. `nil` if unavailable.
    var lastDirection: Double?

    /// Timestamp of the last successful Firebase upload.
    var lastUploadTime: Date?

    /// Local GPS track — saved every 250m, drawn on the map, never uploaded to Firebase.
    var gpsTrack: [LocationPoint]

    // MARK: - Stored — Alert Sync

    /// `true` once the emergency WhatsApp alert has been sent by the Cloud Function.
    var alertSent: Bool

    /// `true` once the alert status has been synced from Firebase to local storage.
    var didSyncAlertStatus: Bool = false

    // MARK: - Init

    init(
        tripId: String,
        tripName: String,
        userName: String,
        phoneNumber: String,
        destination: String,
        destinationLat: Double,
        destinationLng: Double,
        returnTime: Date,
        hasGroup: Bool,
        groupSize: Int,
        carName: String,
        carColor: String,
        is4WD: Bool,
        plateLetters: String,
        plateNumbers: String
    ) {
        self.status = "active"
        self.tripId = tripId
        self.tripName = tripName
        self.userName = userName
        self.phoneNumber = phoneNumber
        self.destination = destination
        self.destinationLat = destinationLat
        self.destinationLng = destinationLng
        self.startTime = Date()
        self.returnTime = returnTime
        self.endedAt = nil
        self.hasGroup = hasGroup
        self.groupSize = groupSize
        self.carName = carName
        self.carColor = carColor
        self.is4WD = is4WD
        self.plateLetters = plateLetters
        self.plateNumbers = plateNumbers
        self.emergencyContacts = []
        self.groupContacts = []
        self.lastKnownLat = 0
        self.lastKnownLng = 0
        self.lastDirection = nil
        self.lastUploadTime = nil
        self.gpsTrack = []
        self.alertSent = false
        self.didSyncAlertStatus = false
    }

    // MARK: - Computed

    /// `true` if the trip is currently active.
    var isActive: Bool { status == "active" }

    /// `true` if the user has not returned by the expected return time.
    var isOverdue: Bool { status == "overdue" }

    /// `true` if the trip has been completed safely.
    var isCompleted: Bool { status == "completed" }
}


// MARK: - Contact

/// A person associated with a trip — either an emergency contact or a group member.
@Model
class Contact {
    var name: String
    var phone: String

    init(name: String, phone: String) {
        self.name = name
        self.phone = phone
    }
}


// MARK: - LocationPoint

/// A single GPS point in the local trip track.
/// Saved every 250m — drawn on the map only, never uploaded to Firebase.
@Model
class LocationPoint {
    var index: Int
    var lat: Double
    var lng: Double

    init(index: Int, lat: Double, lng: Double) {
        self.index = index
        self.lat = lat
        self.lng = lng
    }
}
