//
//  Trip.swift
//  Desert
//
//  Created by Arwa Alkadi on 21/04/2026.
//

import Foundation
import SwiftData

/// A single desert trip — stored locally in SwiftData and synced to Firebase.
@Model
class Trip {
    
    /// Trip lifecycle status — either `"active"` or `"completed"`.
    var status: String
    
    /// Unique trip identifier — generated by Firebase, format: `trip_001`.
    var tripId: String
    
    /// Display name — defaults to the start date if not provided by the user.
    var tripName: String
    
    var userName: String
    var phoneNumber: String
    
    /// Latitude of the last location uploaded to Firebase. `0` if not yet uploaded.
    var lastKnownLat: Double
    
    /// Longitude of the last location uploaded to Firebase. `0` if not yet uploaded.
    var lastKnownLng: Double
    
    /// Heading in degrees at the time of last upload. `nil` if unavailable.
    var lastDirection: Double?
    
    /// Timestamp of the last successful Firebase upload.
    var lastUploadTime: Date?
    
    /// Family members notified if the trip is overdue.
    var emergencyContacts: [Contact]
    
    /// People travelling with the user.
    var groupContacts: [Contact]
    
    var destination: String
    var destinationLat: Double
    var destinationLng: Double
    var startTime: Date
    
    /// Expected return time — used to trigger offline notifications if overdue.
    var returnTime: Date
    
    var hasGroup: Bool
    var groupSize: Int
    var carName: String
    var carColor: String
    var is4WD: Bool
    var plateLetters: String
    var plateNumbers: String
    
    /// Local GPS track — saved every 250m, drawn on the map, never uploaded to Firebase.
    var gpsTrack: [LocationPoint]
    
    /// `true` once the emergency alert/SMS has been sent.
    var alertSent: Bool
    
    init(
        tripId: String,
        tripName: String,
        userName: String,
        phoneNumber: String,
        destination: String,
        destinationLat: Double,
        destinationLng: Double,
        returnTime: Date,
        hasGroup: Bool,
        groupSize: Int,
        carName: String,
        carColor: String,
        is4WD: Bool,
        plateLetters: String,
        plateNumbers: String
    ) {
        self.status = "active"
        self.tripId = tripId
        self.tripName = tripName
        self.userName = userName
        self.phoneNumber = phoneNumber
        self.lastKnownLat = 0
        self.lastKnownLng = 0
        self.lastDirection = nil
        self.lastUploadTime = nil
        self.emergencyContacts = []
        self.groupContacts = []
        self.destination = destination
        self.destinationLat = destinationLat
        self.destinationLng = destinationLng
        self.startTime = Date()
        self.returnTime = returnTime
        self.hasGroup = hasGroup
        self.groupSize = groupSize
        self.carName = carName
        self.carColor = carColor
        self.is4WD = is4WD
        self.plateLetters = plateLetters
        self.plateNumbers = plateNumbers
        self.gpsTrack = []
        self.alertSent = false
    }
    
    /// `true` if the trip is currently active.
    var isActive: Bool { status == "active" }
    
    /// `true` if the trip has been completed.
    var isCompleted: Bool { status == "completed" }
}


// MARK: - Contact

/// A person associated with a trip — either an emergency contact or a group member.
@Model
class Contact {
    var name: String
    var phone: String
    
    init(name: String, phone: String) {
        self.name = name
        self.phone = phone
    }
}


// MARK: - LocationPoint

/// A single GPS point in the local trip track.
/// Saved every 250m — drawn on the map only, never uploaded to Firebase.
@Model
class LocationPoint {
    var lat: Double
    var lng: Double
   
    init(index: Int, lat: Double, lng: Double) {
       
        self.lat = lat
        self.lng = lng
        
    }
}
